###
GET http://localhost:64909/gym

###
GET http://localhost:64909/gym/66fb9fb53bd047aa5d8657bb

###
POST http://localhost:64909/gym
Content-Type: application/json

{
    "name": "Abdurahman",
    "desc": "Rahman desc"
}

###
PUT http://localhost:64909/gym/66fb9fb53bd047aa5d8657bb
Content-Type: application/json

{
    "name": "Abdur Rahman",
    "desc": "Rahman"
}

###
DELETE http://localhost:64909/gym/66fb9f8d3bd047aa5d8657ac